[package]
name = "lattice-graph"
version = "0.1.0"
authors = ["aobatact <aobatact144@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5"
itertools = "0.10"
fixedbitset = "0.4"
smallvec = {version = "1.6", features=["union"]}
